CREATE TABLE rooms(
	id SERIAL NOT NULL PRIMARY KEY,
);

CREATE TABLE students(
	id SERIAL NOT NULL PRIMARY KEY,
	id_room SERIAL NOT NULL REFERENCES rooms(id),
	age INTEGER NOT NULL,
	gender VARCHAR(6) NOT NULL
);
